apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECTNAME
  namespace: $HARBOR_NAMESPACE
  labels:
    app: $PROJECTNAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $PROJECTNAME
  template:
    metadata:
      labels:
        app: $PROJECTNAME
    spec:
      containers:
      - name: $PROJECTNAME
        image: $REGISTRY/$HARBOR_NAMESPACE/$PROJECTNAME:$CURRENT_TIME
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: test-secret
---
apiVersion: v1
kind: Service
metadata:
  name: $PROJECTNAME
  namespace: $HARBOR_NAMESPACE
spec:
  type : NodePort
  selector:
    app: $PROJECTNAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30500
